### ISSUE TITLE
cleaner way to style the website

### ISSUE THREAD

**Issue by AugustinMauroy** [zen-browser/www#26]
Now the project use tailwind in className.
But there are problem with that, it's create spaghetti code.

## So the solution is module css

Module css with tailwind allow us to separate JSX and logic to the style.

here an example:

```tsx
import styles from './component.module.css';
import type { FC } from 'react';

const Component: FC = () => (
    <div className={styles.card}>
        <h1>Hello, World!</h1>
    </div>
);

export default Component;
```

```css
.card {
    @apply bg-white
        border
        border-gray-300
        rounded-lg
        shadow-md
        dark:border-gray-700
        dark:bg-gray-800;

    h1 {
        @apply text-2xl
            font-semibold
            dark:text-white;
    }
}
```
