### ISSUE TITLE
White content flash on dark mode

### ISSUE THREAD

**Issue by Kaedriz** [zen-browser/www#376]
https://github.com/user-attachments/assets/60e61001-3e87-47e5-a8e0-8615e47c4c45

As in the video, bright flash can be seen, even while loading dark mode.

How this could be fixed is up to you, and how do you generate website (SPA, Hybrid or just server rendered). Maybe some cookie, or just color mode detection in plain css which is prefetched. From what I have seen, now, it stores color mode in localStorage, which needs js to access, which in turn does only get interpreted after some milliseconds (but still produces noticeable flash on dark mode).

**Comment by KyleDL101** [comment]
Myself and @Raiden0456 are looking to fix this sometime soon

**Comment by JSGRD22** [comment]
This was fixed for a while, but now it's a black flash on light mode instead...

**Comment by KyleDL101** [comment]
Yes @mr-cheff made dark mode the default mode, so now the page loads dark mode my default first. However, he also deferred the script that loads the theme from local storage, which increases the flash time.

**Comment by Kaedriz** [comment]
You have the following code in `Layout.astro`:
```css
:root {
    --zen-paper: #f2f0e3;
    --zen-dark: #202020;
    --zen-muted: rgba(0, 0, 0, 0.05);

    &[data-theme='dark'] {
      --zen-paper: #202020;
      --zen-dark: #f2f0e3;
      --zen-muted: rgba(255, 255, 255, 0.05);
    }
  }
```

Couldn't this be change to use `prefers-color-scheme` first, then if detected, apply chosen color mode? I presume most users use either only dark/light modes and rarely switch from their preferred. This would fix it for users without explicit set color mode in Zen website. (ex. you have selected dark mode in Firefox/Zen, so you get dark mode CSS)

Code then can be changed to first try browser color pref, then JS would check `localStorage`, if there is any, to change mode to other one. This would still inflict flash on users with explicit set color modes, but would fix it for majority, I guess?

Note that this is just a band-aid solution and not a proper replacement for light/dark mode system.
